### ISSUE TITLE
Error: Call to undefined function Doku_Handler_Parse_Media() on page refresh

### ISSUE THREAD

**Issue by jercle** [jercle/orphanmedia2#1]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/10472533/218954962-e2e20f56-1134-42df-a622-ac5bb4b795df.png">

The above error appears on page refresh. Editing the page removes the error until it is again loaded.

**Comment by Nils98Ar** [comment]
@jercle Any progress on this?

**Comment by UnFefeSauvage** [comment]
I've got a similar problem in another plugin (a custom roughly up-to-date dwmenu).
This function seems to be undefined in only some contexts.

@jercle  Try forcing a cache purge of the page by adding `?purge=true` to your request URL, it temporarily keeps the problem at bay on my side (though I don't quite know why :face_with_diagonal_mouth: ).
(Of course it is not a real solution but it might give us some clue at what's happening here)

For context this is the call stack that leads to my error (it shows DokuWiki is rendering cached content, at least I think):
```
/var/www/dokuwiki-failed/lib/plugins/dwmenu/syntax.php(340)
    #0 /var/www/dokuwiki-failed/inc/parser/renderer.php(126): syntax_plugin_dwmenu->render()
    #1 /var/www/dokuwiki-failed/inc/parserutils.php(691): Doku_Renderer->plugin()
    #2 /var/www/dokuwiki-failed/inc/parserutils.php(158): p_render()
    #3 /var/www/dokuwiki-failed/inc/parserutils.php(97): p_cached_output()
    #4 /var/www/dokuwiki-failed/inc/Ui/PageView.php(67): p_wiki_xhtml()
    #5 /var/www/dokuwiki-failed/inc/Action/Show.php(40): dokuwiki\Ui\PageView->show()
    #6 /var/www/dokuwiki-failed/inc/template.php(120): dokuwiki\Action\Show->tplContent()
    #7 [internal function]: tpl_content_core()
    #8 /var/www/dokuwiki-failed/inc/Extension/Event.php(134): call_user_func_array()
    #9 /var/www/dokuwiki-failed/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #10 /var/www/dokuwiki-failed/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #11 /var/www/dokuwiki-failed/lib/tpl/dokuwiki/main.php(60): tpl_content()
    #12 /var/www/dokuwiki-failed/inc/actions.php(30): include('...')
    #13 /var/www/dokuwiki-failed/doku.php(131): act_dispatch()
    #14 {main}
```

**Comment by Supportedge** [comment]
thanks @jercle for your software.  i have some more info that may (or may not) help.  i only get this bug when the page includes ~~ NOCACHE ~~

i haven't noticed it on page refresh.  i get this bug when i click a link (to a page or media) generated by orphanmedia2 and then press the browser back button.  It doesn't happen all the time, about 1 out of 5 times.

**Comment by dsp77** [comment]
> [@jercle](https://github.com/jercle) Try forcing a cache purge of the page by adding `?purge=true` to your request URL, it temporarily keeps the problem at bay on my side (though I don't quite know why 🫤 ). (Of course it is not a real solution but it might give us some clue at what's happening here)

The ?purge=true option does not work for me, running Release 2024-02-06b "Kaos".
